strictness: high
autodetect: true
doc-warnings: true
test-warnings: true
member-warnings: true

pep257:
  run: true
  disable:
    - D210
    - D212
    - D213
    - D413
    - D407
    - D406
    - D203

pycodestyle:
  disable:
    - E741

pep8:
  run: true
  disable:
    - E741

pylint:
  run: true
  disable:
    - R1729

bandit:
  run: true

pyroma:
  run: true

pyflakes:
  run: true
  disable:
    - F401


mccabe:
  run: true
  disable:
    - MC0001
