strictness: high
autodetect: false
doc-warnings: true
test-warnings: true
member-warnings: true

bandit:
  run: true
  options:
    config: pyproject.toml


pydocstyle:
  run: true
  disable:
    - D200
    - D210
    - D212
    - D213
    - D413
    - D407
    - D406
    - D203

pycodestyle:
  disable:
    - E741
    - E731
    - E203

pylint:
  run: true
  disable:
    - R1729

pyroma:
  run: true

pyflakes:
  run: true
  disable:
    - F401

mccabe:
  run: true
  disable:
    - MC0001
