site_name: "TorrentFile Docs"
site_url: "https://alexpdev.github.io/torrentfile"
repo_url: "https://github.com/alexpdev/torrentfile"
repo_name: "alexpdev/torrentfile"
site_description: "TorrentFile CLI Documentation and Examples"
copyright: "alexpdev 2022"
extra_css: ["stylesheets/extra.css"]
docs_dir: "site"
site_dir: "docs"

theme:
  name: material
  logo: images/torrentfile.png
  favicon: images/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: maroon
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

nav:
  - Home : index.md
  - Usage : Usage.md
  - Overview : Overview.md
  - Changelog : changelog.md
  - License : Apache2.md
  - API : source.md
  - CLI : cli.md
  - commands : commands.md
  - edit : edit.md
  - hasher : hasher.md
  - interactive : interactive.md
  - mixins : mixins.md
  - rebuild : rebuild.md
  - recheck : recheck.md
  - torrent : torrent.md
  - utils : utils.md
  - version : version.md


markdown_extensions:
  - admonition
  - callouts
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - toc:
      permalink: "¤"


plugins:
  - search
  - coverage
  - section-index
  - autorefs
  - mkapi
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            inherited_members: true
            docstring_options:
              ignore_init_summary: yes
            merge_init_into_class: yes
            docstring_section_style: spacy
            show_signature_annotations: true
            show_source: false
            show_submodules: no
            seperate_signature: true
            show_root_heading: true
