site_name: "TorrentFile Docs"
site_url: "https://alexpdev.github.io/torrentfile"
repo_url: "https://github.com/alexpdev/torrentfile"
repo_name: "alexpdev/torrentfile"
site_description: "TorrentFile CLI Documentation and Examples"
copyright: "alexpdev 2022"
extra_css: ["stylesheets/extra.css"]
docs_dir: "site"
site_dir: "docs"

theme:
  name: material
  logo: images/torrentfile.png
  favicon: images/favicon.ico
  features:
    - header.autohide
    - toc.integrate
    - navigation-expand
    - navigation-tabs
    - navigation-instant
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: maroon
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

nav:
  - Home : index.md
  - Usage : usage.md
  - Overview : overview.md
  - Changelog : changelog.md
  - License : Apache2.md
  - API : api.md
  - Coverage: coverage.md
  - Source:
    - Source/index.md
    - Source/cli.md
    - Source/commands.md
    - Source/edit.md
    - Source/hasher.md
    - Source/interactive.md
    - Source/mixins.md
    - Source/rebuild.md
    - Source/recheck.md
    - Source/torrent.md
    - Source/utils.md
    - Source/version.md


markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - toc:
      permalink: "#"
  - callouts
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.caret
  - attr_list
  - def_list
  - meta
  - abbr
  - codehilite
  - smarty
  - sane_lists
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tasklist


plugins:
  - search
  - coverage:
      page_name: coverage
      html_report_dir: htmlcover
  - section-index
  - autorefs
  - mkapi
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            inherited_members: true
            merge_init_into_class: yes
            docstring_section_style: spacy
            show_signature_annotations: true
            show_source: true
            heading_level: 2
            seperate_signature: false
            show_root_full_path: false
            show_root_heading: true
