site_name: TorrentFile Docs
site_url: https://alexpdev.github.io/torrentfile
repo_url: https://github.com/alexpdev/torrentfile
site_description: "TorrentFile CLI Documentation and Examples"
copyright: alexpdev 2022
extra_css: [stylesheets/extra.css]

theme:
  name: material
  logo: images/torrentfile.png
  favicon: images/favicon.ico

nav:
  - HOME : index.md
  - CLI : Commands.md
  - Examples : examples.md
  - API : API.md
  - CHANGELOG : changelog.md
  - LICENSE : Apache2.md
  - SOURCE : source.md


plugins:
  - search
  - autorefs
  - mkapi
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
          rendering:
            show_root_heading: yes

docs_dir: site/
site_dir: docs/
