#! /usr/bin/python3
# -*- coding: utf-8 -*-

#####################################################################
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#####################################################################
import os

TEST_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "top")
PIECE_LENGTH1 = 2 ** 14
PIECE_LENGTH2 = 2 ** 16
PIECE_LENGTH3 = 2 ** 18
PIECE_LENGTH4 = 2 ** 20
PIECE_LENGTH5 = 2 ** 22

PIECE_LENGTHS = [
    PIECE_LENGTH1,
    PIECE_LENGTH2,
    PIECE_LENGTH3,
    PIECE_LENGTH4,
    PIECE_LENGTH5,
]
