name: Workflow for python project

on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install coverage pytest pytest-cov
          pip install pytest-pylint pyben tqdm
          pip install pycodestyle pydocstyle pyroma

      - name: Run tests and collect coverage
        run: |
          pyroma .
          pylint torrentfile
          pycodestyle torrentfile
          pydocstyle torrentfile
          pytest --cov=torrentfile --cov=tests --pylint
          coverage xml -o coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1.1.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
